
class wordLoader:

    def  __init__(self):
        self.wordList = {
            'continu proces': 'Het proces van coördineren en leidinggeven met als oogmerk de doelstellingvan de organisatie te behalen.',
            'efficiëntie': 'Activiteiten uitvoeren op zo’n manier dat er zo weinig mogelijk overschotten zijn(minimale input zorgt voor maximale output, "de dingen goed doen")',
            'effectiviteit':  'Het uitvoeren van de juiste taken om de doelen te bereiken ("de goede dingendoen")',
            'Supply chain': 'Een aaneengeschakelde groep van organisaties die opeenvolgende (economische)activiteiten uitvoeren die nodig zijn om een speciek product of specieke dienst tot bij de klantte krijgen',
            'Outsourcing': 'Bepaalde activiteiten naar andere bedrijven verplaatsen (bv. transport, warehou-sing etc.)',
            'Offshoring': 'Bepaalde activiteiten naar het buitenland verhuizen, binnen je eigen ondernemingof naar een andere (bv. kledingproductie in lageloonlanden, callcenter etc.).',
            'Missie': 'Uniek en algemeen doel van de organisatie. Het omvat de meest fundamentele bestaans-reden van de organisatie',
            'mission statement': 'Formeel geschreven document dat de missie van een onderneming bevat.Vaak een one-pager, folder of pamet naar analogie met religieuze of ideologische symbolen.',
            'Visie':  'Het beeld dat de organisatie heeft over haar toekomst en de manier waarop de missievolbracht kan worden.',
            'synergie': 'Een samenwerkingsverband dat meer oplevert dan wanneer beide partners apart de-zelfde activiteit zouden uitoefenen',
            'Kritische Prestatie Indicatoren (KPI)': 'Kerngetallen om de vooruitgang binnen het bedrijf tecontroleren',
            'Algemene doelstellingen (AMORE)':' Ambitieus, Motiverend, Onderscheidend, Relevant, Echt.',
            'Strategische doelstellingen (MAGIE)': 'Meetbaar, Acceptabel, Gecommuniceerd, Inspirerend,Engagerend.',
            'Operationele doelstellingen (SMART)': 'De concrete vertaling van de algemene of strategischedoelstellingen.   Ze zijn ’concreet’ omdat ze een nadrukkelijke link vertonen met de concrete,gewenste resultaten. Speciek, Meetbaar, Acceptabel, Realistisch, Tijdsgebonden',
            'Stakeholders':  'Een organisatie of persoon die invloed (positief of negatief ) ondervindt van ofkan uitoefenen op de organisatie en dus belangen heeft bij de werking van de organisatie.',
            'Bedrijfstak of sector':  'Verzameling van bedrijven die een gelijkaardige functie hebben in hetvoortbrengingsproces en/of die zich bezighouden met de creatie of verkoop van gelijksoortigegoederen.',       
            'Porter’s 5 forces':' Interne concurrentie, substituten, leveranciers, afnemers & nieuwe toetreders.',
            'merger':' Twee bedrijven besluiten samen om verder te gaan als één groter bedrijf (friendly deal)',
            'Acquisition':' één (groot) bedrijf koopt een (kleiner) bedrijf op, dat volledig opgaat in het grotebedrijf (unfriendly deal)',
            'Zakelijk portfolio':' De verzameling van alle activiteiten van een onderneming.',
            'Concurrentievoordeel':' Dat wat een product/organisatie onderscheidt van andere producten/organisaties',
            'Organisatiestructuur':' De formele structuur van de organisatie op basis waarvan de taken wor-den verdeeld, gegroepeerd en gecoördineerd. Het vormt de basis voor de organisatiehiërarchie',
            'Organogram':' Grafsche voorstelling van de organisatiestructuur',
            'Taakspecialisatie':' Een activiteit wordt uitgesplitst in verschillende taken. Werknemers specialiseren zich in plaats van de hele activiteit uit te voeren',
            'Taakcoördinatie':' Groeperen van taken zodat ze gemakkelijker kunnen worden gecoördineerd',
            'Hiërarchie':'  Ononderbroken gezagslijn die van het hoogste organisatieniveau naar de lagereniveaus loopt.',
            'Lijnmanagement':' Functie draagt direct bij tot de doelstellingen van de organisatie',
            'Stafmanagement':' Functie behoort tot ondersteunende diensten',
            'Gezag':' Algemeen aanvaard recht van een hoger geplaatste om een ondergeschikte te vertellenwat ze moeten doen.',
            'Delegeren':' Overdragen van bevoegdheden (gezag), inclusief verantwoordelijkheid',
            'Verantwoordelijkheid':' Het accepteren van de verplichting dat een toegewezen taak goed wordtuitgevoerd',
            'Span of control (reikwijdte)':' Het aantal werknemers waaraan een manager effectief en effciënt leiding kan geven',
            'Horizontale (platte) organisatiestructuur':'  Organisatie met weinig of geen tussenliggendemanagementlagen',
            'Formalisatie':' De mate waarin binnen de organisatie werkzaamheden worden gestandaardiseerden personeel door regels en procedures wordt aangestuurd',
            'Holding':' Hoogste vennootschap in een groep van maatschappijen, heet (meerderheids)aandeelin alle dochtermaatschappijen.',
            'Rationaliteit':'  Objectief, resultaatgericht en consequent zijn.  Beslissingen baseren op perfectedata om de kans op het bereiken van het doel zo groot mogelijk te maken.',
            'Intuïtie':'  Zich baseren op emotie, eerdere ervaring en beoordelingen.  Ook ethiek, waarden ennormen spelen een grote rol',
            'Beperkte rationaliteit':'  Rationele besluitvorming, gebaseerd op de beschikbare informatie enbinnen de grenzen van het besluitvormingsproces.',
            'Eenvoudig probleem':' Verband oorzaak-gevolg is eenvoudig te beschrijven',
            'Best practice':'  Methode of techniek die eectiever blijkt dan alternatieven om een terugkerenprobleem op te lossen',
            'Gecompliceerd probleem': 'Verband oorzaak-gevolg is niet één op één vast te stellen.',
            'Risico':' De kans dat je iets van waarde verliest door een intentionele interactie met onzekerheid',
            'Machtsafstand':' The extent to which the less powerful members of institutions and organisations within a country expect and accept that power is distributed unequally',
            'individualisme':' The degree of interdependence a society maintains among its members. It hasto do with wheteher people’s self-image is dened in terms of "Iör "We"',
            'Masculiniteit': ' The fundamental issue here is what motivates people, wanting to be the best(masculine) or liking what you do (feminine)',
            'Onzekerheidsvermijding':'  The extent to which the members of a culture feel threatened byambiguous or unknonw situations and have created beliefs and institutions that try to avoidthese.',
            'Lange termijnvisie':'  How every society has to maintain some links with its own past whiledealing with the challenges of the present and future',
            'Attitude': 'Evaluerende uitspraak, zowel positief als negatief, over zaken, mensen of gebeurtenissen',
            'Cognitieve attitude-component':' Komt uit de overtuiging en mening voer een bepaald onder-werp (bv. "liegen is fout")',
            'Affectieve attitude-component': ' Omvat gevoelens en emotie (bv.   "Ik heb die persoon nietgraag, want hij is niet altijd eerlijk").',
            'Gedragscomponent van attitude':' De manier waarop iemand handelt naar aanleiding van deattitude (bv. "Ik ga tijdens de lunch niet naast hem zitten")',
            'Arbeidstevredenheid': 'Iemands algemene attitude ten opzichte van zijn werk.',
            'Betrokkenheid bij het werk':' Mate waarin de werknemer zich met zijn werk identificeert eninzet toont.',
            'Betrokkenheid bij de organisatie':' Mate waarin de werknemer zich met organisatie en doel-stellingen identificeert',
            'Persoonlijkheid':'  Unieke combinatie van psychologische kenmerken die een persoon denië-ren. 5 persoonlijkheidskenmerken',
            'Locus of control':' Mate waarin een persoon zijn lot in eigen handen denkt te hebben',
            'Machiavellisme':' Pragmatisch zijn, emotionele afstand bewaren.',
            'Eigenwaarden': 'Mate waarin iemand waardering voor zichzelf heeft',
            'Zelfcontrole':' Aanpassingsvermogen aan externe factoren.',
            'Risicobereidheid':' Mate waarin iemand bereid is om risico te nemen.',
            'Attributietheorie':'  Bepalen of geobserveerd gedrag kan geattribueerd worden aan interne ofexterne invloeden van de persoon',
            'Personeelsbeleid':' Het geheel van (sociale) maatregelen gericht op de werknemers die de orga-nisatie helpt haar doelstellingen te bereiken.',
            'Human Resources Management (HRM)':'  Een  benadering  van  personeelsbeleid  die  ernaarstreeft competitief voordeel te halen en te behouden door het op een strategische wijze inzettenvan sterk betrokken en bekwame medewerkers, gebruikmakend van verscheidene personeels-technieken.',
            'Werving':' Het opsporen, identiceren en aantrekken van capabele sollicitanten.',
            'Afvloeiing':' Het surplus in het personeelsbestand wegwerken',
            'Validiteit':'  Aantoonbare relatie tussen selectie-instrument en een relevant criterium voor defunctie-uitoefening.',
            'Betrouwbaarheid':' Selectie-instrument meet hetzelfde criterium op een consistente manier',
            'Arbeidsvoorwaarden':' Samenvatting van alle regels waaronder de arbeid wordt verricht. Omvatde voorwaarden voor verloning, beloning, vakantie etc',
            'Verloning':' Het loon dat conform de arbeidsvoorwaarden en het tewerkstellingscontract wordtuitgekeerd als tegenprestatie voor het geleverde werk.',
            'Beloning':'  (Financiële)  extra’s  die  aan  het  loonpakket  worden  toegevoegd  om  uitzonderlijkeprestaties te waarderen.',
            'Extralegale voordelen':' Voordelen (in natura) die door de werkgever kunnen worden aangebo-den ter aanvulling van het loon. Deze zijn vaak scaal interessanter voor de werkgever dan eenloonsverhoging',
            'Loopbaanontwikkeling':'  Opeenvolging van de verschillende functies die een werknemer ge-durende zijn leven vervult.',
            'Organisatiefexibiliteit': 'Het vermogen van een organisatie om te reageren of te anticiperen opwisselende en veranderende eisen die de omgeving aan haar stelt.',
            'Flexibility mix': 'Flexibility of labour, technology, finance etc',
            'Controlability': 'Responsiveness of the organisation',
            'Motivatie':' Het proces waardoor iemands inspanningen energie krijgen en worden gestuurd envolgehouden om een doel te bereiken',
            'Extrinsieke motivatie':'  Motivatie gerelateerd aan tastbare beloningen (bv.  salarisverhoging,bonus, promotie, arbeidsomstandigheden etc)',
            'Intrinsieke motivatie': ' Motivatie gerelateerd aan psychologische beloningen (bv.  appreciatie,gevoel van uitdaging, gevoel iets bereikt te hebben etc).',
            'Theorie X':' Negatief mensbeeld:  werknemers vinden werkend vervelend,  zijn lui,  vermijdenverantwoordelijkheden en hebben veel toezicht nodig.',
            'Theorie Y':' Positief mensbeeld:  werknemers vinden werken leuk, zijn creatief, streven verant-woordelijkheid na en kunnen hun eigen weg vinden.',
            'Taakverbreding':' Het in de breedte uitbreiden van taken door het taakbereik te vergroten',
            'Taakverdieping':' Het in de diepte uitbreiden van taken door toekenning van verantwoordelijkheid',
            'Taakroulatie':' De periodieke verschuiving van een werknemer van de ene taak naar een andere',
            'Taakverrijking':'  Het verticaal uitbreiden van taken waardoor de werknemer meer invloed open zeggenschap over zijn werk krijgt.',
            'Communicatie':' De overdracht en het begrip van kennis',
            'Intermenselijke communicatie':' Communicatie tussen twee of meer personen',
            'Organisatiecommunicatie':' Alle communicatiepatronen, -systemen, en -netwerken in een organisatie.',
            'Formele communicatie':'  Communicatie die binnen de formele structuren van de organisatieplaatsvindt (bv. newsletter, memo etc).',
            'Informele communicatie':' Communicatie tussen organisatieleden die geen onderdeel uitmaaktvan de formele werkstructuren van die organisatie (bv. chatbericht tussen collega’s, water coolertalk etc).',
            'Communicatienetwerk':'  Verschillende patronen van verticale en horizontale communicatie-stromen in een organisatie.',
            'Creativiteit':' De mogelijkheid om ideeën op een unieke wijze te combineren om ongebruikelijkeassociaties te leggen',
            'Innovatie':' Het omzetten van een creatief idee in een winstgeven product, dienst, business model,proces etc.',
            'Productinnovatie':'  Het ontwikkelen en in de markt zetten van een nieuw, herontworpen of -ontwikkeld of wezenlijk verbeterd prduct. Dit kan nieuwe technologie, kwaliteitsverbetering etc.omvatten',
            'Pocesinnovatie':' Het implementeren van een nieuw, herontworpen of -ontwikkeld of wezenlijkverbeterd proces.  Dit kan nieuwe technologie, kwaliteitsverbetering, softwareverandering of -verbetering etc. omvatten',
            'Business model innovatie':' Het implementeren van een nieuw, herontworpen of -ontwikkeldof wezenlijk verbeterde manier waarop het bedrijf plant waarde te creëren voor zijn doelgroepen.Het gaat erom om een nieuw verdienmodel te creëren.',
            'Design thinking':' Het verruimen van het perspectief door het langdurig observeren en bestu-deren van het probleem met het doel een duurzame oplossing te ontwikkelen.',
            'Change manager':' Fungeert als katalysator voor het veranderingsproces en neemt de leiding enverantwoordelijkheid voor het doorvoeren van de verandering.',
            'Organisatieontwikkeling':' Technieken of programma’s voor het veranderen van mensen en deaard en kwaliteit van intermenselijke werkrelaties.',
        }


    def getWordlist(self):
        return self.wordList